[package]
name = "proc-macro2"
version = "1.0.6"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[features]
proc-macro = []
default = ["proc-macro"]

[dependencies]
watt-abi = { path = "macros" }
rustc_lexer = "0.1.0"
